### ISSUE TITLE
Mixed content warning in admin

### ISSUE THREAD

**Issue by coreybullman** [Craftpeak/acf-untappd-beer#3]
Not sure when or why this happened but this is what I'm seeing in the console on beer edit screens. The script is blocking anything from being selected.

![Screen Shot 2019-06-03 at 3 11 04 PM](https://user-images.githubusercontent.com/4294041/58827817-f422d400-8611-11e9-9d49-e6e2d47976f1.jpg)

**Comment by coreybullman** [comment]
Mixed content warnings everywhere...

This is on the `Styles` taxonomy page

![Screen Shot 2019-06-03 at 3 16 07 PM](https://user-images.githubusercontent.com/4294041/58828100-a3f84180-8612-11e9-988a-56e6267ad3a1.jpg)

**Comment by JulienMelissas** [comment]
We think this was related to something else in our codebase... Closing.
